### ISSUE TITLE
Update prepare_dependencies.py download paths

### ISSUE THREAD

**Issue by Kurtoid** [google/google-api-cpp-client#33]

**Comment by bloodcarter** [comment]
+1

**Comment by SurferJeffAtGoogle** [comment]
I guess that's why I'm seeing this when I run `./prepare_dependencies.py`?
```
make[1]: Leaving directory `/usr/local/google/home/rennie/gitrepos/google-api-cpp-client/external_dependencies/openssl-1.0.1m/tools'
installing libcrypto.a
installing libssl.a
cp libcrypto.pc /usr/local/google/home/rennie/gitrepos/google-api-cpp-client/external_dependencies/install/lib/pkgconfig
chmod 644 /usr/local/google/home/rennie/gitrepos/google-api-cpp-client/external_dependencies/install/lib/pkgconfig/libcrypto.pc
cp libssl.pc /usr/local/google/home/rennie/gitrepos/google-api-cpp-client/external_dependencies/install/lib/pkgconfig
chmod 644 /usr/local/google/home/rennie/gitrepos/google-api-cpp-client/external_dependencies/install/lib/pkgconfig/libssl.pc
cp openssl.pc /usr/local/google/home/rennie/gitrepos/google-api-cpp-client/external_dependencies/install/lib/pkgconfig
chmod 644 /usr/local/google/home/rennie/gitrepos/google-api-cpp-client/external_dependencies/install/lib/pkgconfig/openssl.pc
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++  Finished installing openssl-1.0.1m
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading glog-0.3.3.tar.gz from http://google-glog.googlecode.com/files/glog-0.3.3.tar.gz: 
 0.0% of 49 bytes
 100.0% of 49 bytes

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>  Unpacking glog-0.3.3.tar.gz into glog-0.3.3
Traceback (most recent call last):
  File "./prepare_dependencies.py", line 1162, in <module>
    processed_packages = installer.Run()
  File "./prepare_dependencies.py", line 1144, in Run
    self.ProcessDependencyOrDie(key)
  File "./prepare_dependencies.py", line 1132, in ProcessDependencyOrDie
    value.Process()
  File "./prepare_dependencies.py", line 539, in Process
    self.Unpackage()
  File "./prepare_dependencies.py", line 377, in Unpackage
    tar = tarfile.open(archive_filename)
  File "/usr/lib/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

```
